variables:
  DOCKERHUB_IMAGE: nekoimi/jenkins-dind:latest

stages:
  - build
  - push

build-image:
  stage: build
  only:
    - master
  tags:
    - docker
  script:
    - docker build -t $DOCKERHUB_IMAGE .

push-image:
  stage: push
  only:
    - master
  tags:
    - docker
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
    - docker push $DOCKERHUB_IMAGE
