variables:
  DOCKERHUB_IMAGE: nekoimi/jenkins-plus:latest

stages:
#  - build
  - deploy

build:
  stage: build
  only:
    - master
  tags:
    - docker
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
    - docker build -t $DOCKERHUB_IMAGE .
    - docker push $DOCKERHUB_IMAGE

deploy:
  stage: deploy
  only:
    - master
  tags:
    - ssh
    - deploy
  script:
    - pwd
    - ls -al
    - id
    - hostname
