variables:
  DOCKERHUB_IMAGE: nekoimi/jenkins-plus:latest

stages:
  - build

build-job:
  stage: build
  only:
    - master
  tags:
    - docker
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
    - docker build -t $DOCKERHUB_IMAGE .
    - docker push $DOCKERHUB_IMAGE
