variables:
  DOCKERHUB_IMAGE: nekoimi/jenkins-plus:latest

stages:
  - build
  - push

build-job:
  stage: build
  only:
    - master
  tags:
    - docker
  script:
    - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_ACCESS_TOKEN
    - docker build -t $DOCKERHUB_IMAGE .

push-job:
  stage: push
  only:
    - master
  tags:
    - docker
  script:
    - docker push $DOCKERHUB_IMAGE
