variables:
  DOCKERHUB_IMAGE: nekoimi/jenkins-plus:latest

stages:
  - build
  - push
  - deploy

build-image:
  stage: build
  only:
    - master
  tags:
    - docker
  script:
    - docker build -t $DOCKERHUB_IMAGE .

push-image:
  stage: push
  only:
    - master
  tags:
    - docker
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
    - docker push $DOCKERHUB_IMAGE

deploy:
  stage: deploy
  only:
    - master
  tags:
    - ssh
    - deploy
  script:
    - cd $COMPOSE_DEPLOY_WORKSPACE/jenkins
    - docker compose up -d
